### ISSUE TITLE
Use gulp for script tasks

### ISSUE THREAD

**Issue by pedrohml** [FCO/JSGames#27]

**Comment by FCO** [comment]
Why do you think that would be better than npm?

**Comment by pedrohml** [comment]
Gulp support chain of dependencies tasks and complex build tasks like minify/coffeescript/imagetools in a easy way

**Comment by FCO** [comment]
We just use browserify... (And some shell script magic)

**Comment by FCO** [comment]
What do you think of showing us a example of how would the branch level_creator (the most complex build script) with gulp?

**Comment by pedrohml** [comment]
I agree npm is enough for now. But I think we will need decouple tasks from package.json to improve project build and structure since it supports shell/js code

**Comment by pedrohml** [comment]
Consider look the commit below using gulp to generate brickbreaker levels (branch: _level_creator_):
50bbdc95334b3a2419a926c425a6c5dc695030d6

**Comment by FCO** [comment]
That looks great!

**Comment by FCO** [comment]
Maybe we should have a gulpfile to do the brickbreaker Magic inside the samples/brickbreaker dir and the root gulpfile should call it... Does that make sense?

**Comment by pedrohml** [comment]
It seems too much better.
Done: 724ec5099fca47f3d6cbeacdda0f79b95c8eb8ea

**Comment by FCO** [comment]
You are on fire! 😀

**Comment by pedrohml** [comment]
What do you think use gulp to build asset files to create game bundles ?
My concern is that the project needs node jvm to run, but we can create asset files able to run directly in browser.
Gulp can help to replace _require_ commands and so on to allow these assets to run in browser.

**Comment by FCO** [comment]
I didn't get it... Could you show me a example?

**Comment by pedrohml** [comment]
Ok, as soon as I can. I will open another issue for that and close this.

**NOTE: The initial steps for this issue were done in _level_creator_ branch**

**Comment by FCO** [comment]
Maybe using this would be a good idea: https://github.com/betsol/gulp-require-tasks/blob/master/README.md

**Comment by FCO** [comment]
could you, please, take a look? e9cc51067
